# Site settings
title: Godlovezk Blog
SEOTitle: 我的博客 | Godlovezk Blog
header-img: img/home-bg.jpg
email: 947739614@qq.com
description: "Godlovezk 的个人博客，与你一起发现更大的世界。"
keyword: "码农 搬砖 "
url: "https://godlovezk.github.io/"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
weibo_username:     godlovezk
zhihu_username:     godlovezk
github_username:    godlovezk
twitter_username:   godlovezk
#facebook_username:  godlovezk
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Disqus settings
disqus_username: godlovezk

# Netease setttings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "这里应该写一段装逼的话<br>可是我还没想好写些什么!"
sidebar-avatar: /img/avatar-hux.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
    #     title: "Su",
    #     href: "1http://su.gallery/"
    # },{
        title: "测试1",
        href: "1http://mida.re/"
    },{
        title: "测试1",
        href: "1http://qianduan.guru/"
    },{
        title: "测试1",
        href: "1http://lingyu.wang/"
    },{
        title: "测试1",
        href: "1http://hmqk1995.github.io"
    },{
        title: "测试1",
        href: "1http://ebnbin.com/"
    },{
        title: "测试1",
        href: "1http://blog.smdcn.net"
    },{
        title: "测试1",
        href: "1http://xieminis.me/"
    },{
        title: "测试1",
        href: "1http://dhong.co"
    },{
        title: "测试1",
        href: "1http://ingf.github.io/"
    },{
        title: "测试1",
        href: "1http://wepiaofei.github.io/blog/"
    }
]

theme: jekyll-theme-time-machine